Repository creppyfm/DeleGate, pull requests merged in 2023-05, with the labels that each got.

#5 Kenson/add readme
  README.md
  server/.gitignore
Labels: documentation

#7 Update README
  README.md
Labels: documentation

#8 Established connection to MongoDB cluster
  server/pom.xml
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/resources/application.properties
  server/src/main/resources/com/creppyfm/server/application.properties
Labels: enhancement

#10 Kenson/add client
  .gitignore
  client/.eslintrc.cjs
  client/.gitignore
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/vite.svg
  client/src/App.css
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/components/Example.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: enhancement

#11 GET test endpoint
  server/src/main/java/com/creppyfm/server/controller/UserController.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/repository/UserRepository.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
Labels: enhancement

#14 OAuth2 Google and GitHub SSO + dummy controller
  server/.gitignore
  server/pom.xml
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
  server/src/main/java/com/creppyfm/server/controller/LoginController.java
  server/src/main/java/com/creppyfm/server/controller/UserController.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/repository/UserRepository.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
  server/src/main/resources/application.properties
Labels: enhancement

#20 Added editor files to gitignore
  .gitignore
Labels: documentation

#21 Kenson/testing colors
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/Example.tsx
  client/src/components/Header.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/scss/styles.scss
  client/vite.config.ts
  docs/colors.md
Labels: enhancement

#31 Kenson/add footer
  client/public/GitHub.svg
  client/public/LinkedIn.svg
  client/public/vite.svg
  client/src/App.tsx
  client/src/components/Footer.tsx
Labels: enhancement

#33 ProjectMember association
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/model/Project.java
  server/src/main/java/com/creppyfm/server/service/ProjectService.java
Labels: enhancement

#41 User Modifications
  server/src/main/java/com/creppyfm/server/controller/UserController.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
Labels: enhancement

#48 Foli/task delegation implementation
  server/pom.xml
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/repository/TaskRepository.java
  server/src/main/java/com/creppyfm/server/service/ProjectService.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
Labels: enhancement

#51 Fix for issue #50
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/model/User.java
Labels: bug

#53 Provider Enum
  server/src/main/java/com/creppyfm/server/enumerated/Provider.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
Labels: enhancement

#60 I'm so sorry.
  server/pom.xml
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/authentication/CustomOAuth2User.java
  server/src/main/java/com/creppyfm/server/authentication/CustomOAuth2UserService.java
  server/src/main/java/com/creppyfm/server/authentication/GitHubEmail.java
  server/src/main/java/com/creppyfm/server/authentication/GitHubEmailFetcher.java
  server/src/main/java/com/creppyfm/server/authentication/OAuth2Controller.java
  server/src/main/java/com/creppyfm/server/authentication/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/creppyfm/server/config/HttpSessionConfig.java
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
  server/src/main/java/com/creppyfm/server/controller/LoginController.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/repository/UserRepository.java
  server/src/main/resources/application.properties
Labels: enhancement

#65 Kenson/use session
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/pages/Home.tsx
  client/src/pages/LoginPage.tsx
  client/src/utils/SessionContext.ts
Labels: enhancement

#66 Foli/user session association
  server/pom.xml
  server/src/main/java/com/creppyfm/server/authentication/CustomOAuth2UserService.java
  server/src/main/java/com/creppyfm/server/authentication/OAuth2Controller.java
  server/src/main/java/com/creppyfm/server/authentication/OAuth2LoginSuccessHandler.java
  server/src/main/java/com/creppyfm/server/authentication/SessionService.java
  server/src/main/java/com/creppyfm/server/config/HttpSessionConfig.java
  server/src/main/java/com/creppyfm/server/config/OpenApiConfig.java
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
  server/src/main/java/com/creppyfm/server/controller/HomeController.java
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/controller/UserController.java
  server/src/main/java/com/creppyfm/server/data_transfer_object_model/UserDataTransferObject.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/repository/UserRepository.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
  server/src/main/resources/application.properties
Labels: documentation, enhancement

#67 Kenson/dashboard
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/react.svg
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/pages/PageNotFound.tsx
  client/src/pages/dashboard/DashboardRouter.tsx
  client/src/pages/dashboard/default/DashboardPage.tsx
  client/src/pages/dashboard/default/ProjectCard.tsx
  client/src/pages/dashboard/project/ProjectPage.tsx
Labels: enhancement

#68 Kenson/implement logout
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/pages/Home.tsx
  client/src/pages/dashboard/DashboardRouter.tsx
  client/src/pages/dashboard/default/DashboardPage.tsx
  client/src/pages/dashboard/default/ProjectCard.tsx
  client/src/pages/dashboard/project/ProjectPage.tsx
  client/src/scss/styles.scss
  client/src/utils/routeProtection.tsx
  client/vite.config.ts
  server/src/main/java/com/creppyfm/server/authentication/OAuth2Controller.java
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
Labels: enhancement

#69 Modified login redirect to '/' instead of '/login'.
  server/src/main/java/com/creppyfm/server/authentication/OAuth2Controller.java
Labels: enhancement

#71 Modified securityConfig to push invalidated sessions to /.
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
Labels: bug

#74 ProjectController Modifications
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/data_transfer_object_model/ProjectResponse.java
  server/src/main/java/com/creppyfm/server/service/ProjectService.java
Labels: enhancement

#78 Foli/openai api modifications
  server/src/main/java/com/creppyfm/server/config/SecurityConfig.java
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/ChatMessage.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/ChatResponseChoice.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatRequest.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatResponse.java
  server/src/main/java/com/creppyfm/server/service/ProjectService.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
  server/src/main/resources/application.properties
Labels: enhancement

#79 foli/openai-response-toJSON
  server/src/main/java/com/creppyfm/server/data_transfer_object_model/StepDataTransferObject.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
Labels: enhancement
