Repository creppyfm/DeleGate, pull requests merged in 2023-06, with the labels that each got.

#80 foli/task-generation
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
Labels: enhancement

#92 foli/hot-mods
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/controller/UserController.java
  server/src/main/java/com/creppyfm/server/data_transfer_object_model/TaskDataTransferObject.java
  server/src/main/java/com/creppyfm/server/enumerated/Phase.java
  server/src/main/java/com/creppyfm/server/model/Project.java
  server/src/main/java/com/creppyfm/server/model/ProjectMembers.java
  server/src/main/java/com/creppyfm/server/model/Step.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
  server/src/main/java/com/creppyfm/server/service/UserService.java
Labels: enhancement

#95 foli/enum-integration
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/data_transfer_object_model/ProjectResponse.java
  server/src/main/java/com/creppyfm/server/enumerated/Phase.java
  server/src/main/java/com/creppyfm/server/model/Project.java
  server/src/main/java/com/creppyfm/server/service/ProjectService.java
Labels: enhancement

#94 Kenson/project view context provider
  client/src/App.tsx
  client/src/pages/dashboard/DashboardRouter.tsx
  client/src/pages/dashboard/default/DashboardPage.tsx
  client/src/pages/dashboard/default/ProjectCard.tsx
  client/src/pages/dashboard/project/ProjectPage.tsx
  client/src/pages/dashboard/task/TaskPage.tsx
  client/src/utils/GetProjectData.ts
  client/src/utils/GetUserData.ts
Labels: enhancement

#96 foli/data-association-fix
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/model/Project.java
  server/src/main/java/com/creppyfm/server/repository/StepRepository.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
Labels: bug

#97 Kenson/build task flow
  client/src/pages/dashboard/default/NewProjectForm.tsx
  client/src/pages/step/StepPage.tsx
  client/src/utils/GetProjectData.ts
  client/src/utils/mockProjectList.ts
  client/src/utils/routeProtection.tsx
  client/vite.config.ts
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/model/Project.java
  server/src/main/java/com/creppyfm/server/model/ProjectMembers.java
  server/src/main/java/com/creppyfm/server/model/Step.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/model/User.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
Labels: enhancement

#98 foli/json-toString
  server/src/main/java/com/creppyfm/server/controller/ProjectController.java
  server/src/main/java/com/creppyfm/server/controller/StepController.java
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
Labels: bug, enhancement

#99 foli/task-decomposition
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
Labels: enhancement

#100 foli/hot-fix
  server/src/main/java/com/creppyfm/server/controller/TaskController.java
  server/src/main/java/com/creppyfm/server/model/Task.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/service/StepService.java
  server/src/main/java/com/creppyfm/server/service/TaskService.java
Labels: bug

#107 foli/update-urls
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/authentication/OAuth2Controller.java
  server/src/main/java/com/creppyfm/server/config/OpenApiConfig.java
  server/src/main/java/com/creppyfm/server/config/WebSocketConfig.java
  server/src/main/java/com/creppyfm/server/controller/HomeController.java
Labels: enhancement

#108 foli/hot-envfix
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/config/HttpSessionConfig.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/openai_raw_handlers/OpenAIAPIRawManager.java
Labels: bug

#109 foli/hot-envfix
  server/pom.xml
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/config/HttpSessionConfig.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/openai_raw_handlers/OpenAIAPIRawManager.java
Labels: bug

#110 C'mon
  server/src/main/java/com/creppyfm/server/HelloApplication.java
  server/src/main/java/com/creppyfm/server/config/HttpSessionConfig.java
  server/src/main/java/com/creppyfm/server/openai_chat_handlers/OpenAIChatAPIManager.java
  server/src/main/java/com/creppyfm/server/openai_raw_handlers/OpenAIAPIRawManager.java
Labels: bug

#111 Modified CORS to accept new origin.
  server/src/main/java/com/creppyfm/server/HelloApplication.java
Labels: bug

#119 foli/hot-envfix
  server/src/main/java/com/creppyfm/server/controller/ChatController.java
  server/src/main/java/com/creppyfm/server/service/ChatService.java
Labels: enhancement

#120 foli/hot-envfix
  server/src/main/java/com/creppyfm/server/controller/ChatController.java
Labels: bug

#121 foli/chatController-fix
  server/src/main/java/com/creppyfm/server/controller/ChatController.java
Labels: bug

#122 foli/stream-endpoint
  server/src/main/java/com/creppyfm/server/controller/ChatController.java
Labels: bug

#137 foli/stream-hotfix
  server/src/main/java/com/creppyfm/server/HelloApplication.java
Labels: enhancement

#138 Fixed filename
  client/Procfile
Labels: bug
